site_name: CST2232, Conception de Systèmes Temps Réel à base du microcontrôleur STM32F4
site_description: Cours de Master en Génie Logiciel Industriel
site_author: Ir Paul S. Kabidu
site_url: https://Plkab.github.io/cst2232

theme: mkdocs

markdown_extensions:
  - tables
  - attr_list

nav:
  - Accueil: index.md

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true   # optionnel : ajoute aussi la date de création
      type: date                    # format : date, datetime, timeago