site_name: CST2232, Conception de Systèmes Temps Réel à base du microcontrôleur STM32F4
site_description: Cours de Master en Génie Logiciel Industriel
site_author: Ir Paul S. Kabidu
site_url: https://Plkab.github.io/cst2232

theme:
  name: material
  language: fr
  favicon: images/favicon.ico
  palette:
    - scheme: default
      primary: indigo
      accent: cyan
    - scheme: slate
      primary: indigo
      accent: cyan
  font:
    text: Roboto
    code: Roboto Mono
  features: []   # pas de navigation, pas de TOC

markdown_extensions:
  - tables
  - attr_list

plugins: []   # aucun plugin

nav: []       # supprime le menu "Accueil"
