# Nom du site
site_name: CST2232, Conception de Systèmes Temps Réel à base du microcontrôleur STM32F4
site_description: Cours Master Génie Logiciel Industriel
site_author: Paul S. Kabidu
site_url: https://Plkab.github.io/cst2232

# Configuration du thème
theme:
  name: material
  language: fr
  favicon: images/favicon.ico
  palette:
    - scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Mode sombre
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mode clair
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - search.suggest
    - search.highlight
    - content.code.copy

# Extensions Markdown
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins
plugins:
  - search
  - glightbox

